// Copyright 2022 Jose Pablo Ramirez (@jpe230)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// 基础点设置针脚配置
#define POINTING_DEVICE_CS_PIN GP21
#define POINTING_DEVICE_SCLK_PIN GP22
#define POINTING_DEVICE_SDIO_PIN GP20

// adns5050配置选项
// #define ADNS5050_CS_PIN   POINTING_DEVICE_CS_PIN
// #define ADNS5050_SCLK_PIN POINTING_DEVICE_SCLK_PIN
// #define ADNS5050_SDIO_PIN POINTING_DEVICE_SDIO_PIN

// pmw3360配置选项
#define PMW33XX_CS_PIN POINTING_DEVICE_CS_PIN
#define PMW33XX_CPI 600
#define POINTING_DEVICE_INVERT_Y
#define PMW33XX_LIFTOFF_DISTANCE 0x04
// #define ROTATIONAL_TRANSFORM_ANGLE 0



// 触控板配置选项
// #define CIRQUE_PINNACLE_DIAMETER_MM 35
// #define CIRQUE_PINNACLE_CURVED_OVERLAY
// #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE // Circular scroll.
// #define CIRQUE_PINNACLE_SPI_CS_PIN GP21
// #define POINTING_DEVICE_ROTATION_90


// vial配置
#define VIAL_KEYBOARD_UID {0x2B, 0x3C, 0x7E, 0x52, 0x60, 0x3E, 0xFE, 0x52}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 6 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 0 }

#define VIAL_COMBO_ENTRIES 20
#define DYNAMIC_KEYMAP_MACRO_COUNT 50

#define DYNAMIC_KEYMAP_LAYER_COUNT 7

