QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_LVGL_INTEGRATION = yes
QUANTUM_PAINTER_DRIVERS = gc9a01_spi

# 加入vial支持
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

SRC += pic/animation.qgf.c

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
# POINTING_DEVICE_DRIVER = adns5050
